### ISSUE TITLE
hMRI Toolbox error in MATLAB R2023a with the development version of SPM

### ISSUE THREAD

**Issue by inhuszar** [hMRI-group/hMRI-toolbox#63] opened 2023-04-13 13:51 UTC
Both SPM and hMRI-toolbox were installed from Git repositories (up to date as of 13 April 2023).
See the following traceback:

```
tbx_cfg_hmri
Brace indexing is not supported for variables of this type.

Error in cfg_callbuiltin (line 29)
    [varargout{:}] = builtin(varargin{:});

Error in indexing (line 68)
            [varargout{1:nargout}] = cfg_callbuiltin('subsref',val,subs(2:end));

Error in tbx_scfg_hmri_proc_US>cfg_expr (line 309)
            if strcmp(v.val{j}.tag, varargin{i})

Error in tbx_scfg_hmri_proc_US (line 90)
rstruct = eval(['preproc8',cfg_expr(preproc8, 'data')]);

Error in tbx_scfg_hmri_proc (line 43)
proc_modul.values  = {tbx_scfg_hmri_proc_US tbx_scfg_hmri_proc_Dartel tbx_scfg_hmri_proc_smooth};

Error in tbx_cfg_hmri (line 46)
hmri.values  = {tbx_scfg_hmri_config tbx_scfg_hmri_dicom_import tbx_scfg_hmri_autoreorient tbx_scfg_hmri_imperf_spoil tbx_scfg_hmri_B1_create tbx_scfg_hmri_create tbx_scfg_hmri_quality tbx_scfg_hmri_proc tbx_scfg_hmri_QUIQI};

```

**Comment by halirutan** [comment] 2023-04-14 08:57
@inhuszar Can you include what exact operating system you are using for completeness?

**Comment by lukeje** [comment] 2023-04-14 12:20
@inhuszar Unfortunately I wasn't able to reproduce this using Matlab R2023a on a linux system. Which tool or pipeline in the hMRI toolbox were you trying to run when you got this error?

**Comment by lukeje** [comment] 2023-04-14 12:32
Though one thing occurs to me: when you say you got SPM from a github repository, do you mean this one: 
[https://github.com/spm/spm12](https://github.com/spm/spm12), or this one: [https://github.com/spm/spm](https://github.com/spm/spm)? Currently we only support the stable version of SPM (that is, SPM12), and not the development version (now just known as "SPM").

**Comment by inhuszar** [comment] 2023-04-14 14:13
> Though one thing occurs to me: when you say you got SPM from a github repository, do you mean this one: https://github.com/spm/spm12, or this one: https://github.com/spm/spm? Currently we only support the stable version of SPM (that is, SPM12), and not the development version (now just known as "SPM").

Thank you very much, @lukeje! When I install SPM from the repository at https://github.com/spm/spm12, the hMRI toolbox starts working as expected. Previously, I used the other SPM repository on my Linux Mint 21.1 system with Matlab R2023a, which led me to the above error. More precisely, I was seeing the "hMRI tools - not available!" button in the menu, and from there I followed the source code, executed tbx_cfg_hmri, and saw the error. Since it seemed like a genuine syntax error, I thought it could be related to MATLAB's most recent version change. To be honest, I still don't know what difference in the SPM versions could trigger an error like this. Thank you once again!

**Comment by lukeje** [comment] 2023-04-14 14:54
Ah, it's good that the solution was so simple. I updated the documentation on the [wiki](https://github.com/hMRI-group/hMRI-toolbox/wiki/GetStarted) to make clearer that SPM12 is required. We'll have to look more deeply into what caused the problem with the development version of SPM, but for now I'll close this issue.

**Closed by lukeje** 2023-04-14 14:54 UTC

**Comment by gllmflndn** [comment] 2023-05-12 12:17
You might have already fixed this in your development version but the issue here is due to a change in the development version of SPM (to implement lazy-loading in the batch interface): configuration structs can now contain a function handle instead of a parsed tree so it needs to be evaluated if you reuse it outside of SPM's batch interface:

```matlab
preproc8 = spm_cfg_preproc8;
if isa(preproc8.val,'function_handle')
    preproc8.val = feval(preproc8.val);
end
```

**Comment by lukeje** [comment] 2023-05-26 09:08
Thanks for the hint @gllmflndn. 

@Barisevrenugur would you like to try out Guillaume's suggested fix? It looks like only a small change would be needed to the code to get it to work.
