### ISSUE TITLE
nifti inputs from BIDS dataset

### ISSUE THREAD

**Issue by octomike** [hMRI-group/hMRI-toolbox#45] opened 2022-05-03 13:22 UTC
Hello. I'm visiting this toolbox again while helping to prepare a BIDS conforming dataset using an MPM protocol with the `RF_map` B1+ correction method.

I'm currently wondering if there is a real need to use the included, patched `spm_dicom_convert` method to generate nifti images or whether we could pass the files that we (automatically) generated and curated with heudiconv/dcm2niix et al.

Specifically, I'd like to know if:

1. the code in this toolbox expects a specific json sidecar file format to function properly
2. this toolbox is doing something special for splitting the two images from the single Siemens rf_map dicom series we need for the B1+ bias correction 
3. we really have to gunzip niftis :smiling_face_with_tear:

**Comment by lukeje** [comment] 2022-05-03 13:40
1. Thanks to the efforts of @nbeliy the toolbox accepts bids-compliant sidecar files. However I think there are still some non-bids fields which the toolbox expects to find. If I recall correctly, though, these are all B1-mapping (mainly 3D-EPI B1 mapping) related. If you run into problems with the bids support, then he should be able to help.
2. I think the toolbox doesn't do anything special for splitting the data other than saving them as two separate files. The important thing is that the first input should be the anatomical volume and the second input should be the flip angle map (which is then scaled during map creation to get the B1 map in percent units). Remember that if you have a 4D nifti then you will need to use `filename,1` and `filename,2` to access the individual volumes in the batch system.
3. Yes, we use spm_read_vols to read the data which does not (as far as I know) support gzip-ed niftis. It would be nice to move to the new in-built nifti tools in Matlab (which do support gzip-ed niftis), but they have their own problems.

**Comment by nbeliy** [comment] 2022-05-06 09:45
Hi @octomike, sorry for the late responce

1. Indeed, in theory, you can run on bidsified dataset with the standard sidecar json. But you must be prepared to deal with some missing metadata (depending how you bidsified it). If something is missing (look for warning messages in the terminal output), you can always define them in the local defaults file. But I will suggest just to complete the sidecar json.

From memory, you will need RepetitionTime/RepetitionTimeExiation, EchoTime, FieldStrength, MixingTime and FlipAngleSeries.

The last one is not from bids (so for sure you will not have it in your TB1EPI), and contains the list of flip angles corresponding to the `flip-` index, for ex:
```json
"FlipAngleSeries": [65.0, 70.0, 75.0, 80.0, 85.0]
```

Another important thing,  hMRI-toolbox expect the input of B! maps sorted by echo and flip (in the same order as in raw dicom names): echo-1_flip-01, echo-2_flip-01,  echo-1_flip-02, echo-2_flip-02, so be careful when you add them.

P.S. @lukeje  The echo/flip sorting is extremely annoying, may be we need to fix it somehow

**Comment by lukeje** [comment] 2022-07-18 10:51
@octomike I'm going to close this issue now, as I assume that no news is good news (i.e. that you were able to get the toolbox to work with the bids-ified data). If there are any specific issues with the processing, feel free to re-open this issue.

@nbeliy You probably need to push Issue #16; the problem is still that the SE/STE mapping parameters are not generally stored in the DICOM header and so have to be inferred. This in turn necessitates a strict input order...

**Closed by lukeje** 2022-07-18 10:51 UTC

**Comment by nbeliy** [comment] 2022-07-19 14:00
@lukeje Not sure if I got the problem correctly, but in bids one supposed to have all parameters available directly and not inferred.
In other words all acquisition settings conflict should be resolved during the bidsification and not during analysis.

If I misunderstood the issue, then I could look into (mind I'm not MRI physicist, and all these parameters are mostly Chinese for me).

**Comment by lukeje** [comment] 2022-07-19 14:18
@nbeliy As SE/STE B1 mapping parameters (e.g. SE and STE flip angles, mixing time, etc.) are not currently stored in the DICOM header because of technological limitations, the parameters need to be inferred at some point. This can either be during the bids-ification process, or during the input process. However before this can be generalised, some sort of standardisation needs to be done on the sequence side. This is the topic of Issue #16.
